parameters:
  neos_foo:

services:

  neos_eventsourcing_event_eventTypeResolver:
    class: Neos\EventSourcing\Event\Resolver\FullyQualifiedClassNameResolver

  neos_eventsourcing_eventStore_eventNormalizer:
    class: Neos\EventSourcing\EventStore\EventNormalizer
    arguments:
      $eventTypeResolver: "@neos_eventsourcing_event_eventTypeResolver"

  neos_eventsourcing_symfonybridge_command_setupCommand:
    class: Neos\EventSourcing\SymfonyBridge\Command\SetupCommand
    tags: ["console.command"]
    arguments:
      # TODO
      $doctrineAppliedEventsStorageSetup: "@neos_eventsourcing_symfonybridge_eventlistener_appliedeventsstorage_doctrineAppliedEventsStorageSetup"
      $container: "@Psr\\Container\\ContainerInterface"

  neos_eventsourcing_symfonybridge_eventlistener_appliedeventsstorage_doctrineAppliedEventsStorageSetup:
    class: Neos\EventSourcing\SymfonyBridge\EventListener\AppliedEventsStorage\DoctrineAppliedEventsStorageSetup
    arguments:
      $connection: "@Doctrine\\DBAL\\Connection"


  neos_eventsourcing_symfonybridge_command_internalFooCommand:
    class: Neos\EventSourcing\SymfonyBridge\Command\InternalCatchUpEventListenerCommand
    tags: [ "console.command" ]
    arguments:
      $container: "@Psr\\Container\\ContainerInterface"
      $connection: "@Doctrine\\DBAL\\Connection"

  Neos\EventSourcing\SymfonyBridge\Transport\ConsoleCommandTransport: ~
  Neos\EventSourcing\SymfonyBridge\Transport\AsyncTransportInterface: '@Neos\EventSourcing\SymfonyBridge\Transport\ConsoleCommandTransport'
