# this services.yaml is loaded via {@see NeosEventSourcingExtension}.
services:

  neos_eventsourcing_event_eventTypeResolver:
    class: Neos\EventSourcing\SymfonyBridge\Event\Resolver\FullyQualifiedClassNameResolver

  neos_eventsourcing_eventStore_eventNormalizer:
    class: Neos\EventSourcing\EventStore\EventNormalizer
    arguments:
      $eventTypeResolver: "@neos_eventsourcing_event_eventTypeResolver"

  neos_eventsourcing_symfonybridge_command_setupCommand:
    class: Neos\EventSourcing\SymfonyBridge\Command\SetupCommand
    tags: ["console.command"]
    arguments:
      $doctrineAppliedEventsStorageSetup: "@neos_eventsourcing_symfonybridge_eventlistener_appliedeventsstorage_doctrineAppliedEventsStorageSetup"
      $container: "@service_container"

  neos_eventsourcing_symfonybridge_command_catchUpCommand:
    class: Neos\EventSourcing\SymfonyBridge\Command\InternalCatchUpEventListenerCommand
    tags: [ "console.command" ]
    arguments:
      $container: "@service_container"
      $connection: "@Doctrine\\DBAL\\Connection"

  neos_eventsourcing_symfonybridge_command_replayCommand:
    class: Neos\EventSourcing\SymfonyBridge\Command\ProjectionReplayCommand
    tags: [ "console.command" ]
    arguments:
      $container: "@service_container"
      $connection: "@Doctrine\\DBAL\\Connection"

  neos_eventsourcing_symfonybridge_eventlistener_appliedeventsstorage_doctrineAppliedEventsStorageSetup:
    class: Neos\EventSourcing\SymfonyBridge\EventListener\AppliedEventsStorage\DoctrineAppliedEventsStorageSetup
    arguments:
      $connection: "@Doctrine\\DBAL\\Connection"

  Neos\EventSourcing\SymfonyBridge\Transport\ConsoleCommandTransport:
    arguments:
      $projectDir: "%kernel.project_dir%"
      $environment: "%kernel.environment%"

  Neos\EventSourcing\SymfonyBridge\Transport\MessengerTransport:
  Neos\EventSourcing\SymfonyBridge\Transport\AsyncTransportInterface: '@Neos\EventSourcing\SymfonyBridge\Transport\ConsoleCommandTransport'
